# Generated by Django 5.0.6 on 2024-07-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_imagemveiculo_veiculo_imagem"),
    ]

    operations = [
        migrations.AddField(
            model_name="imagemveiculo",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
